### ISSUE TITLE
I can't figure out what ['data'] means

### ISSUE THREAD

**Issue by osazemeu** [IkoroVictor/paystack-ruby#1]
I can't figure out what `['data']`  in this line of code means;
```auth_url = result['data']['authorization_url']```

`['authorization_url']` is for positive response or success page but I have read through the docs and couldn't figure out what params am passing to 'data'.

Could you help me out? Am I missing anything??

**Comment by IkoroVictor** [comment]
Here is a sample response format from paystack for initializing transactions

`{
  "status": true,
  "message": "Authorization URL created",
  "data": {
    "authorization_url": "https://standard.paystack.co/pay/0peioxfhpn",
    "access_code": "0peioxfhpn",
    "reference": "7PVGX8MEk85tgeEpVDtD"
  }
}`

You can see the `data` JSON object there.

When JSON.parse is called, it deserializes the object into a hashset.

**Comment by osazemeu** [comment]
thanks
