### ISSUE TITLE
   RestClient::BadRequest (400 Bad Request):

### ISSUE THREAD

**Issue by wayneskillz** [IkoroVictor/paystack-ruby#13]
Hi, i am getting a consistent (400 - Bad Request Error) on the initializeTransaction function. i am initializing in my controller. see screenshot. 

![screen shot 2017-05-15 at 3 40 54 pm](https://cloud.githubusercontent.com/assets/2619507/26063164/1d6532a8-3985-11e7-8fd8-b0d8bc389cfe.png)

**Comment by paingha** [comment]
I experience same when trying to setup subscription. Did you by chance find a fix?

**Comment by wayneskillz** [comment]
Hello @paingha , There are two basic things i did that helped me resolve this.

1. Make sure all environment variables are set in production. i.e. if you are getting this error in production. you can use the "figaro" gem to set this. see  [here](https://github.com/laserlemon/figaro)

2. Restart your server and try again.

My observation:
I think there is a time frame for each call to the initialize transaction method. calling it more than once for an auth url within that time frame can give you the "Bad Request" error. So, try and ensure you are not having multiple calls to the initialize transaction method within a few seconds and you should be good.

This is just my observation and you can try it as a temporary solution to this until we get a permanent solution or an update.

Regards :)

**Comment by paingha** [comment]
Hi @wayneskillz thanks for the reply. I still get some errors I haven't used paystack before do you think you can help me take a look at my subscription controller, please. I will really appreciate it. https://github.com/paingha/subscriptions

**Comment by wayneskillz** [comment]
Okay @paingha.  No problem

**Comment by wayneskillz** [comment]
Can you specify what errors exactly you are getting @paingha

**Comment by paingha** [comment]
@wayneskillz I get a bad request sometimes and sometimes a 404 http client not found

**Comment by wayneskillz** [comment]
@paingha, a 404 error means your app cannot communicate with the paystack server. This is possible if you have poor or bad network connection.

I took a look at your subscriptions controller. The only possible reason i see for you to get the Bad request error is if your paystack keys are not properly initialized. How are you setting this keys in your app. can you specify how you did set them?

**Comment by paingha** [comment]
Hi @wayneskillz I have environment variables setup in Heroku environment variables. Customer creation method works well just subscription and new transaction method gives an error. The new customer method is in my user model. And that works fine.

**Comment by wayneskillz** [comment]
@paingha , you said you have them setup on heroku. did you set them locally too? send me an email "georgedelson@gmail.com" i may need to do a remote session with you to help resolve this.

**Comment by dev-men** [comment]
@paingha did Your issue is resolved?
I'm also getting the same error. 
Creating a customer works fine. But can't commit the transaction.
@wayneskillz can You help please?

**Comment by wayneskillz** [comment]
@dev-men can you share your repo with me so i can take a look at your code.  email me at "georgedelson[at]gmail.com

**Comment by paingha** [comment]
@dev-men Hi yes the issue was resolved. This is an example of how I ended up implementing it https://github.com/paingha/subscriptions

**Comment by eyewritecode** [comment]
In case you land here having the same Issue, Just know that this is a common error that happens when your environment variables are not **"set"**.  
I put this in quotes because you might have set it but not available in the current terminal session!
You can check if the ENV KEY is available with:
```
printenv <yourenvkey>
```
if you get nothing then it means you need to readd it or just put it in your `bash` files

**Comment by oomis** [comment]
@dev-men I'm also getting the same error.
Creating a customer works fine. But can't commit the transaction.
Can you help, please?

**Comment by oomis** [comment]
I was able to fix it by ensuring the email address is valid
