### ISSUE TITLE
[Escalated from Paystack Support] Create subscription gives 404

### ISSUE THREAD

**Issue by ibrahimlawal** [IkoroVictor/paystack-ruby#14]
*Apeel It* sent:

I ran into some trouble trying to integrate paystack with my ruby on rails web app. I have installed the paystack gem and bundle installed it. I am trying to create a subscription for the web app. I was able to implement the customer creation method which works fine but the subscription method keeps on giving me a 404 HTTP client not found error.

**Comment by paingha** [comment]
Good day, please I'm encountering some problems while trying to implement subscriptions with this gem. I'm currently using these versions: Paystack Gem version 0.1.6, rails version 5.0.0.1, ruby version of ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]. I was able to implement the create customer methof in my user model and it works perfectly but the subscription method keeps on throwing a 404 http client not found error.

**Comment by ibrahimlawal** [comment]
@paingha I looked through your records. The customers you are attempting to subscribe do not have any authorizations. Subscribing a customer requires that they have already paid you in the past.
