### ISSUE TITLE
How to notify an action after Successful or Unsuccessful payment

### ISSUE THREAD

**Issue by dev-men** [IkoroVictor/paystack-ruby#16]
I'm using Paystack-Ruby Gem for paystack Payment gateway 1st time.

I'm successful in loading the Paystack page where Customer can enter his/her card or bank detail. And pay the amount.

![sejvm](https://user-images.githubusercontent.com/31854716/38062310-afbcedc2-330c-11e8-9c42-c7529744f3fe.png)

I'm using Paystack-Ruby Gem for paystack Payment gateway 1st time.

I'm successful in loading the Paystack page where Customer can enter his/her card or bank detail. And pay the amount.

But I'm unable to figure out How can I know transaction is performed?

How will I go to the next page?
When a Transaction is initiated I just have 3 things

1. Reference Number
2. Access Code
3. Paystack Authorization URL
After that Paystack page is loaded. And I have a dead-end.

Your help will be appreciated.

Thanks.

**Comment by wayneskillz** [comment]
Hello @dev-men , you can query your unique reference code to verify the status of a transaction. 
you can also specify a callback url after a transaction is completed. 

you can go through the api docs to familiarize yourself with the entire process. it will help you understand what the paystack-ruby gem helps you achieve.

https://developers.paystack.co/docs

**Comment by dev-men** [comment]
@wayneskillz Thank You for Your response. 
I figured it out. 
I just have to mention the "Call Back URL" in PayStack. 
Either the payment is successful or not, the call will be returned to mentioned Call Back URL. From where I can proceed further.

**Comment by wayneskillz** [comment]
@dev-men thats great. Thanks for the update.

**Comment by Andi1204** [comment]
![Screenshot_20211118-234236_Gmail](https://user-images.githubusercontent.com/94629815/142447803-7d3df0bf-8921-41db-b6dd-1b9a4164ddae.jpg)

I'm unable to figure out How can I know transaction is performed?

How will I go to the next page?

Your help will be appreciated.

Thanks.
