### ISSUE TITLE
Dependency on mime-types

### ISSUE THREAD

**Issue by timigod** [IkoroVictor/paystack-ruby#2]
I have mime-types 3.1 (in Gemfile.lock) and a lot of gems generally depend on anything above 1.16. Rails 5.0.0 allows 1.16 to 4.0. Is there any reason it's locked to between 3.0 and 1.16 or it's something that can be easily changed (to 4.0)?

**Comment by IkoroVictor** [comment]
Sorry i didn't get that. Is this a question relating to the project?

**Comment by timigod** [comment]
Yes it is. Your gem is locked to mime types 3.0 and 1.16 because of the version of rest-client you're requiring. 
I made a pull request to fix this by changing the ruby and rest client dependency versions
